steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/tejas/backend:latest'
      - './backend'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/tejas/backend:latest'

timeout: 600s
