/**
 * Core type definitions for the Tejas frontend.
 *
 * These types mirror the backend models and define the WebSocket
 * message protocol between the client and server.
 */

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export type VictimStatus =
  | "immediate"
  | "delayed"
  | "minor"
  | "deceased"
  | "unknown";

export type ResourceType =
  | "ambulance"
  | "fire_truck"
  | "hazmat_unit"
  | "police"
  | "helicopter";

export type SeverityLevel = "critical" | "urgent" | "moderate";

export type ConnectionStatus =
  | "disconnected"
  | "connecting"
  | "connected"
  | "error"
  | "reconnecting";

export type SessionState =
  | "idle"
  | "connecting"
  | "active"
  | "paused"
  | "closed";

// ---------------------------------------------------------------------------
// Domain Models
// ---------------------------------------------------------------------------

export interface GeoLocation {
  latitude: number;
  longitude: number;
  accuracy?: number;
  timestamp?: number;
}

export interface Victim {
  victimId: string;
  status: VictimStatus;
  injuries?: string;
  treatmentGiven?: string;
  locationDescription?: string;
  notes?: string;
  timestamp: number;
}

export interface DispatchRecord {
  dispatchId: string;
  resourceType: ResourceType;
  severity: SeverityLevel;
  etaMinutes: number;
  status: string;
  notes?: string;
  timestamp: number;
}

export interface HazmatInfo {
  chemicalName: string;
  unNumber?: string;
  hazardClass?: string;
  safeDistanceFt: number;
  ppeRequired: string[];
  immediateActions: string[];
}

export interface ToolCallInfo {
  name: string;
  args: Record<string, unknown>;
  result?: Record<string, unknown>;
  status: "executing" | "completed" | "failed";
  timestamp: number;
}

// ---------------------------------------------------------------------------
// Incident State (aggregated HUD data)
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// GenMedia: Scene Image (from Google Imagen 3 via generate_scene_report tool)
// ---------------------------------------------------------------------------

export interface SceneImage {
  /** base64-encoded JPEG generated by Google Imagen 3 */
  imageB64: string;
  mimeType: string;
  sceneDescription: string;
  victimCount: number;
  hazards: string[];
  incidentId: string | null;
  timestamp: number;
}

export interface IncidentState {
  incidentId: string | null;
  victims: Victim[];
  dispatches: DispatchRecord[];
  hazards: HazmatInfo[];
  toolCalls: ToolCallInfo[];
  transcripts: string[];
  isActive: boolean;
  /** Tactical scene maps generated by Generate Imagen 3 */
  sceneImages: SceneImage[];
}

// ---------------------------------------------------------------------------
// WebSocket Messages
// ---------------------------------------------------------------------------

/** Messages sent from the client to the server */
export type ClientMessageType =
  | "audio"
  | "video"
  | "session_init"
  | "text"
  | "end_turn"
  | "ping";

export interface ClientMessage {
  type: ClientMessageType;
  data?: string | Record<string, unknown>;
}

/** Messages received from the server */
export type ServerMessageType =
  | "audio"
  | "transcript"
  | "tool_call"
  | "tool_result"
  | "status"
  | "heartbeat"
  | "turn_complete"
  | "error"
  | "pong"
  // GenMedia: Google Imagen 3 scene map generated by generate_scene_report tool
  | "scene_image";

export interface ServerMessage {
  type: ServerMessageType;
  data?: unknown;
  mime_type?: string;
  timestamp?: number;
}

export interface AudioServerMessage extends ServerMessage {
  type: "audio";
  data: string; // base64 PCM
  mime_type: string;
}

export interface TranscriptServerMessage extends ServerMessage {
  type: "transcript";
  data: string;
}

export interface ToolCallServerMessage extends ServerMessage {
  type: "tool_call";
  data: {
    name: string;
    args: Record<string, unknown>;
    status: "executing";
  };
}

export interface ToolResultServerMessage extends ServerMessage {
  type: "tool_result";
  data: {
    name: string;
    result: Record<string, unknown>;
    status: "completed";
  };
}

export interface StatusServerMessage extends ServerMessage {
  type: "status";
  data: {
    status: string;
    message: string;
  };
}

export interface HeartbeatServerMessage extends ServerMessage {
  type: "heartbeat";
  data: {
    session_id: string;
    uptime_seconds: number;
    audio_chunks_sent: number;
    audio_chunks_received: number;
    video_frames_sent: number;
    tool_calls_executed: number;
  };
}

export interface ErrorServerMessage extends ServerMessage {
  type: "error";
  data: {
    message: string;
  };
}

/** GenMedia: Google Imagen 3 tactical scene map */
export interface SceneImageServerMessage extends ServerMessage {
  type: "scene_image";
  data: {
    image_b64: string;
    mime_type: string;
    scene_description: string;
    victim_count: number;
    hazards: string[];
    incident_id: string | null;
  };
}

// ---------------------------------------------------------------------------
// Session Metrics
// ---------------------------------------------------------------------------

export interface SessionMetrics {
  sessionId: string;
  uptimeSeconds: number;
  audioChunksSent: number;
  audioChunksReceived: number;
  videoFramesSent: number;
  toolCallsExecuted: number;
}

// ---------------------------------------------------------------------------
// Audio Configuration
// ---------------------------------------------------------------------------

export interface AudioConfig {
  sampleRate: number;
  channels: number;
  chunkDurationMs: number;
}

export const DEFAULT_AUDIO_CONFIG: AudioConfig = {
  sampleRate: 16000,
  channels: 1,
  chunkDurationMs: 100,
};

// ---------------------------------------------------------------------------
// Video Configuration
// ---------------------------------------------------------------------------

export interface VideoConfig {
  fpsMin: number;
  fpsMax: number;
  resolution: number;
  quality: number;
}

export const DEFAULT_VIDEO_CONFIG: VideoConfig = {
  fpsMin: 2,
  fpsMax: 10,
  resolution: 480,
  quality: 0.4,
};
